### ISSUE TITLE
How do you override association methods?

### ISSUE THREAD

**Issue by andrewferk** [Bajena/ams_lazy_relationships#68]
AMS provides a very easy way to [override association methods](https://github.com/rails-api/active_model_serializers/blob/0-10-stable/docs/general/serializers.md#overriding-association-methods) and apply a scope:

```rb
class PostSerializer < ActiveModel::Serializer
  has_many :comments do
    object.comments.active
  end
end
```

Is there an easy way to do this with this library?

**Comment by stokarenko** [comment]
It's easy to do for AMS since it does not care about N+1 ))

Lazy relationships are using `ActiveRecord#preload` stuff under the hood, so here we can handle only the same things which you can pass to `.preload` method - `:comments` but not `comments.active`.

Shorter way to achieve you goal might be defining

```ruby
class Post < AR::Base
  has_many :active_comments, -> { where active: true }, class_name: 'Comment', ..
end
```

, then use such relation as lazy relationship )

**Comment by andrewferk** [comment]
Thank you @stokarenko. This makes sense to me.
